"""Close the native recorder if the controller quits, crashes, or closes its pipe."""

import json
import select
import subprocess
import sys


def run(command, control, lock_fd=None):
    child = subprocess.Popen(
        command, stdin=subprocess.PIPE, pass_fds=() if lock_fd is None else (lock_fd,)
    )
    try:
        while child.poll() is None:
            ready, _, _ = select.select([control], [], [], 1)
            if ready:
                control.read(1)  # q or EOF: both request stop; no orphan microphone.
                break
    finally:
        if child.poll() is None:
            try:
                child.stdin.write(b"q\n")
                child.stdin.flush()
            except BrokenPipeError:
                pass
            try:
                child.wait(timeout=10)
            except subprocess.TimeoutExpired:
                child.terminate()
                try:
                    child.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    child.kill()
                    child.wait()
    return child.returncode


if __name__ == "__main__":
    # Arguments are generated by Panther, never read from game data.
    raise SystemExit(run(json.loads(sys.argv[1]), sys.stdin.buffer, int(sys.argv[2])))
