const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const origin='https://panther.place',api='https://test.execute-api.us-west-2.amazonaws.com';
const jwt='test.'+Buffer.from(JSON.stringify({exp:Date.now()/1000+3600,'cognito:username':'example-editor'})).toString('base64url')+'.test';
const key=id=>`games/test-game/assets/${id}/original/image.png`;
const rawKey='games/test-game/assets/raw/original/room.wav';
const checksum=bytes=>crypto.createHash('sha256').update(bytes).digest('base64');
async function fixture(page,context,{failure=false,development=false,imagesReady=true}={}){
 const images=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=600;canvas.height=300;const c=canvas.getContext('2d');c.fillStyle='#dfd1aa';c.fillRect(0,0,600,300);c.strokeStyle='#829da2';c.lineWidth=28;c.beginPath();c.moveTo(250,0);c.bezierCurveTo(50,170,430,160,270,300);c.stroke();c.fillStyle='#39382e';c.font='22px serif';c.fillText('Riverlands',220,36);c.font='18px serif';c.fillText('Harbor',75,200);c.fillText('Hills',440,90);return canvas.toDataURL('image/png').split(',')[1];});
 const image=Buffer.from(images,'base64'),files=new Map(),uploads=[],generations=[],deletions=[];let fail=failure,job=null;
 const assets=[{key:key('atlas'),name:'image.png',kind:'map',contentType:'image/png',size:image.length,metadata:{title:'Riverlands atlas',tags:['map']}},{key:key('keep'),name:'image.png',kind:'blueprint',contentType:'image/png',size:image.length,metadata:{title:'Keep floor plan'}},{key:key('harbor'),name:'image.png',kind:'location',contentType:'image/png',size:image.length,metadata:{title:'Harbor at dusk'}}];
 for(const asset of assets)files.set(asset.key,{...asset,bytes:image,sha256:checksum(image)});
 const wav=Buffer.alloc(44+16000*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
 files.set(rawKey,{key:rawKey,name:'room.wav',contentType:'audio/wav',size:wav.length,sha256:checksum(wav),bytes:wav,metadata:{},kind:null});
 const jsonKey='games/test-game/assets/notes/original/notes.json';assets.push({key:jsonKey,name:'notes.json',kind:'unknown',contentType:'application/json',metadata:{title:'Session notes'}});
 await context.route(`${api}/**`,route=>{
  const req=route.request(),url=new URL(req.url()),respond=(json,status=200)=>route.fulfill({json,status,headers:{'access-control-allow-origin':origin}});
  if(url.pathname==='/assets/delete'){const body=req.postDataJSON();deletions.push(body);const file=files.get(body.key);expect(body.sha256).toBe(file.sha256);files.delete(body.key);const index=assets.findIndex(asset=>asset.key===body.key);if(index>=0)assets.splice(index,1);return respond({deleted:true,key:body.key});}
  if(url.pathname==='/generation-capabilities')return respond({images:imagesReady});
  if(url.pathname==='/assets')return respond({assets,cursor:null});
  if(url.pathname==='/asset-generation'){
   if(req.method()==='POST'){const body=req.postDataJSON();generations.push(body);if(fail){fail=false;return respond({error:'Service temporarily unavailable'},503);}job={...body,jobId:'a'.repeat(64),status:'QUEUED',assetKey:null};return respond(job);}
   if(!url.searchParams.has('jobId'))return respond({jobs:job?[job]:[],cursor:null});
   const asset={key:key('generated'),name:'image.png',kind:job.type,contentType:'image/png',size:image.length,metadata:{title:job.name}};files.set(asset.key,{...asset,bytes:image,sha256:checksum(image)});job={...job,status:'PUBLISHED',assetKey:asset.key};return respond(job);
  }
  if(url.pathname==='/uploads'){const body=req.postDataJSON();uploads.push(body);const logical=`games/${body.gameId}/assets/${body.assetId}/original/${body.filename}`;files.set(logical,{key:logical,kind:body.kind,name:body.filename,size:body.size,metadata:body.metadata,contentType:body.contentType,sha256:body.sha256,pending:true});return respond({key:logical,url:`https://files.example/upload?key=${encodeURIComponent(logical)}`,headers:{'Content-Type':body.contentType,'Content-Length':String(body.size),'If-None-Match':'*','x-amz-checksum-sha256':body.sha256}});}
  if(url.pathname==='/object-url'){const file=files.get(url.searchParams.get('key'));if(!file||file.pending)return respond({error:'Object not found'},404);return respond({...file,bytes:undefined,filename:file.name,url:`https://files.example/read?key=${encodeURIComponent(file.key)}`,expiresIn:300});}
  if(url.pathname==='/objects'){const prefix=url.searchParams.get('prefix')||'games/test-game/';return respond({prefixes:prefix==='games/test-game/'?['games/test-game/assets/']:[],objects:prefix==='games/test-game/'?[]:[{key:rawKey,name:'room.wav',size:wav.length,lastModified:'2026-10-01T00:00:00Z'}],nextCursor:null});}
  if(url.pathname==='/recordings/live')return respond({recordings:[]});
  return respond({games:[{id:'test-game',name:'Riverlands'}],game:{id:'test-game',name:'Riverlands'},players:[],memberships:[],characters:[],chapters:[],assets:[],objects:[],prefixes:[],cursor:null});
 });
 await context.route('https://files.example/**',route=>{const url=new URL(route.request().url()),file=files.get(url.searchParams.get('key'));if(url.pathname==='/upload'){file.bytes=route.request().postDataBuffer();expect(checksum(file.bytes)).toBe(file.sha256);file.pending=false;return route.fulfill({status:200});}return route.fulfill({body:file.bytes,contentType:file.contentType});});
 await context.route(`${origin}/**`,route=>{const pathname=new URL(route.request().url()).pathname;if(pathname.startsWith('/auth/'))return route.fulfill({json:{id_token:jwt,expires_in:3600}});if(pathname==='/config.js')return route.fulfill({contentType:'application/javascript',body:`window.PANTHER_CONFIG={development:${development},apiUrl:'${api}',clientId:'test',cognitoDomain:'https://test.amazoncognito.com',redirectUri:'${origin}/'};`});if(pathname==='/vendor/model-viewer.min.js')return route.fulfill({contentType:'application/javascript',body:''});const root=path.resolve(__dirname,'../../web/media-explorer');let source=path.resolve(root,'.'+pathname);if(!source.startsWith(root+path.sep)||!fs.existsSync(source)||!fs.statSync(source).isFile())source=path.join(root,'index.html');return route.fulfill({body:fs.readFileSync(source),contentType:source.endsWith('.js')?'application/javascript':source.endsWith('.css')?'text/css':'text/html'});});
 return{uploads,generations,deletions,image,files};
}
for(const width of [1280,390])test(`Typed Assets library uploads and generates maps at ${width}px`,async({page,context},testInfo)=>{
 await page.setViewportSize({width,height:900});const{uploads,generations,image}=await fixture(page,context);await page.goto(`${origin}/games/test-game/assets`);
 const library=page.getByRole('region',{name:'Assets',exact:true});await expect(page.getByRole('link',{name:'Assets',exact:true})).toHaveAttribute('aria-current','page');
 await library.getByRole('button',{name:'Maps',exact:true}).click();await expect(library.getByRole('button',{name:'Riverlands atlas Map · PNG',exact:true})).toBeVisible();await expect(library.getByRole('button',{name:'Keep floor plan Blueprint · PNG',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Upload',exact:true}).click();const upload=page.getByRole('form',{name:'Upload asset'});await expect(upload.getByRole('combobox',{name:'Asset type',exact:true})).toHaveText('Map');await upload.getByLabel('Name (optional)',{exact:true}).fill('Northern route');await upload.getByLabel('File',{exact:true}).setInputFiles({name:'route.png',mimeType:'image/png',buffer:image});await upload.getByRole('button',{name:'Upload asset',exact:true}).click();await expect(library.getByRole('button',{name:'Northern route Map · PNG',exact:true})).toBeVisible();expect(uploads).toHaveLength(1);expect(uploads[0]).toMatchObject({gameId:'test-game',kind:'map',sha256:checksum(image)});
 await page.getByRole('button',{name:'Generate',exact:true}).click();const generate=page.getByRole('form',{name:'Generate asset'});await generate.getByLabel('Name',{exact:true}).fill('Eastern coast');await generate.getByLabel('Prompt',{exact:true}).fill('A regional map with a harbor, river, and wooded hills.');const submit=generate.getByRole('button',{name:'Generate asset',exact:true});await submit.scrollIntoViewIfNeeded();await expect(submit).toBeInViewport();expect(await submit.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);await expect(page.getByRole('dialog',{name:'Generate asset',exact:true})).toBeVisible();await page.screenshot({path:testInfo.outputPath(`assets-form-${width}.png`),fullPage:true});await submit.click();await expect(page.getByRole('button',{name:'Open asset',exact:true})).toBeVisible({timeout:10000});expect(generations).toHaveLength(1);expect(generations[0]).toMatchObject({type:'map',name:'Eastern coast'});expect(generations[0].operationId).toMatch(/^[a-f0-9]{32}$/);
 await page.getByRole('button',{name:'Open asset',exact:true}).click();await expect(page.locator('#preview-body img')).toBeVisible();await page.getByRole('button',{name:'Close preview',exact:true}).click();await page.reload();await expect(library.getByRole('button',{name:'Eastern coast Map · PNG',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:testInfo.outputPath(`assets-library-${width}.png`),fullPage:true});
});
test('Generation retries retain an immutable request and survive route navigation',async({page,context})=>{
 const{generations}=await fixture(page,context,{failure:true});await page.goto(`${origin}/games/test-game/assets`);const library=page.getByRole('region',{name:'Assets',exact:true});await page.getByRole('button',{name:'Generate',exact:true}).click();let form=page.getByRole('form',{name:'Generate asset'});await form.getByRole('combobox',{name:'Asset type',exact:true}).click();await page.getByRole('option',{name:'Blueprint',exact:true}).click();await form.getByLabel('Name',{exact:true}).fill('Keep layout');await form.getByLabel('Prompt',{exact:true}).fill('A keep floor plan with a courtyard.');await form.getByRole('button',{name:'Generate asset',exact:true}).click();await expect(form).toContainText('Service temporarily unavailable');await expect(form.getByLabel('Prompt',{exact:true})).toBeDisabled();
 await form.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('link',{name:'Dashboard',exact:true}).click();await page.getByRole('navigation',{name:'Panther sections'}).getByRole('link',{name:'Assets',exact:true}).click();await page.getByRole('button',{name:'Generate',exact:true}).click();form=page.getByRole('form',{name:'Generate asset'});await expect(form.getByLabel('Prompt',{exact:true})).toHaveValue('A keep floor plan with a courtyard.');await form.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('button',{name:'Open asset',exact:true})).toBeVisible({timeout:10000});expect(generations).toHaveLength(2);expect(generations[1]).toEqual(generations[0]);
});
for(const width of [1280,390])test(`Parent folder precedes file links and an unindexed WAV opens normally at ${width}px`,async({page,context},testInfo)=>{
 await page.setViewportSize({width,height:900});await fixture(page,context);await page.goto(`${origin}/games/test-game/media?folder=${encodeURIComponent('games/test-game/assets/raw/original/')}`);const browser=page.locator('.media-browser');const first=browser.locator('tbody tr').first();await expect(first.getByRole('button',{name:'Parent folder',exact:true})).toBeVisible();await browser.getByRole('button',{name:'room.wav',exact:true}).click();await expect(page.locator('#preview-body audio')).toBeVisible();await expect(page.getByText('This asset is not in the current catalog. Reload the page to try again.',{exact:true})).toHaveCount(0);await expect(page.locator('#asset-links')).toBeEmpty();await page.screenshot({path:testInfo.outputPath(`unknown-wav-${width}.png`)});await page.getByRole('button',{name:'Close preview',exact:true}).click();await browser.getByRole('button',{name:'Parent folder',exact:true}).click();await expect(page).toHaveURL(/folder=games%2Ftest-game%2Fassets%2Fraw%2F$/);await page.goto(`${origin}/games/test-game/media?folder=${encodeURIComponent('games/test-game/')}`);await expect(browser.getByRole('button',{name:'Parent folder',exact:true})).toHaveCount(0);
});

for(const width of [1280,390])test(`Asset cards expose file formats and a blocked generation has a concise focused error at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});await fixture(page,context);
 await context.route(`${api}/asset-generation*`,route=>{const job={jobId:'blocked',gameId:'test-game',name:'Harbor image',status:'ATTENTION',message:'Image generation is unavailable. Check the server configuration.'};return route.fulfill({json:new URL(route.request().url()).searchParams.has('jobId')?job:{jobs:[job],cursor:null}});});
 await page.goto(`${origin}/games/test-game/assets`);const library=page.getByRole('region',{name:'Assets',exact:true});
 await expect(library.getByRole('button',{name:'Riverlands atlas Map · PNG',exact:true})).toBeVisible();
 await expect(library.getByRole('button',{name:'Session notes Other · JSON',exact:true})).toBeVisible();
 await expect(library.getByRole('button',{name:'Session notes Other · JSON',exact:true}).locator('svg')).toHaveClass(/lucide-file-code/);
 await library.getByRole('button',{name:'View progress',exact:true}).click();await expect(page.getByRole('dialog',{name:'Harbor image',exact:true}).getByRole('alert')).toHaveText('Image generation is unavailable. Check the server configuration.');await expect(page.getByText(/panther assets worker/)).toHaveCount(0);
 await expect(library.locator('progress')).toHaveCount(0);
});

for(const width of [1280,390])test(`Browse files is a subtle link before Upload and opens the file view at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});await fixture(page,context);await page.goto(`${origin}/games/test-game/assets`);const library=page.getByRole('region',{name:'Assets',exact:true}),link=page.getByRole('link',{name:'Browse files',exact:true});await expect(link).toBeVisible();await expect(link).toBeInViewport();const box=await link.boundingBox(),region=await library.boundingBox(),uploadBox=await page.getByRole('button',{name:'Upload',exact:true}).boundingBox(),generateBox=await page.getByRole('button',{name:'Generate',exact:true}).boundingBox();expect(box.x+box.width).toBeLessThanOrEqual(uploadBox.x);expect(uploadBox.x+uploadBox.width).toBeLessThanOrEqual(generateBox.x);expect(box.y+box.height/2).toBeCloseTo(uploadBox.y+uploadBox.height/2,0);expect(box.y).toBeLessThan(region.y+60);await page.screenshot({path:test.info().outputPath(`assets-top-link-${width}.png`),fullPage:true});const original=await link.evaluate(el=>({font:getComputedStyle(el).fontSize,height:el.getBoundingClientRect().height}));await link.click();await expect(page).toHaveURL(/assets\?folder=games%2Ftest-game%2F/);const back=page.getByRole('link',{name:'Back to assets',exact:true});await expect(back).toBeVisible();const backBox=await back.boundingBox(),headerBox=await page.locator('#explorer .explorer-heading').boundingBox();expect(backBox.x+backBox.width).toBeCloseTo(headerBox.x+headerBox.width,0);expect(await back.evaluate(el=>getComputedStyle(el).fontSize)).toBe(original.font);await back.click();await expect(page).toHaveURL(`${origin}/games/test-game/assets`);
});

 test('Local Assets disables image generation when the worker is unavailable',async({page,context})=>{
 await fixture(page,context,{development:true,imagesReady:false});await page.goto(`${origin}/games/test-game/assets`);
 const generate=page.getByRole('button',{name:'Generate',exact:true});await expect(generate).toBeDisabled();await expect(generate).toHaveAttribute('title','Image generation is unavailable');await expect(page.getByRole('button',{name:'Upload',exact:true})).toBeEnabled();
 });

for(const width of [1280,390])test(`Assets header actions match Videos dimensions and placement at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});await fixture(page,context);await page.goto(`${origin}/games/test-game/assets`);const heading=page.locator('#explorer .explorer-heading'),upload=heading.getByRole('button',{name:'Upload',exact:true}),generate=heading.getByRole('button',{name:'Generate',exact:true});await expect(upload).toBeVisible();await expect(generate).toBeVisible();const measured=await generate.evaluate(el=>{const r=el.getBoundingClientRect(),style=getComputedStyle(el);return{height:r.height,font:style.fontSize,weight:style.fontWeight,padding:style.padding,border:style.borderRadius,y:r.y,right:r.right};});const up=await upload.evaluate(el=>{const r=el.getBoundingClientRect(),style=getComputedStyle(el);return{height:r.height,font:style.fontSize,weight:style.fontWeight,padding:style.padding,border:style.borderRadius,y:r.y};});for(const key of ['height','font','weight','padding','border','y'])expect(up[key]).toBe(measured[key]);expect(measured.height).toBe(36);const headingRect=await heading.boundingBox();expect(measured.right).toBeLessThanOrEqual(headingRect.x+headingRect.width);expect(measured.right).toBeGreaterThan(headingRect.x+headingRect.width-(width<600?36:120));const searchRect=await page.getByRole('searchbox',{name:'Search assets'}).boundingBox();expect(searchRect.y-headingRect.y-headingRect.height).toBeLessThanOrEqual(18);for(const button of [upload,generate])expect(await button.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);await page.getByRole('navigation',{name:'Panther sections'}).getByRole('link',{name:'Episodes',exact:true}).click();const video=page.getByRole('button',{name:'Create Episode',exact:true});await expect(video).toBeVisible();const v=await video.evaluate(el=>{const style=getComputedStyle(el);return{height:el.getBoundingClientRect().height,font:style.fontSize,weight:style.fontWeight,padding:style.padding,border:style.borderRadius};});for(const key of ['height','font','weight','padding','border'])expect(v[key]).toBe(measured[key]);
});

for(const width of [1280,390])test(`Asset delete confirms, cancels and preserves a rejected asset at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});const{deletions}=await fixture(page,context);await page.goto(`${origin}/games/test-game/assets`);const remove=page.getByRole('button',{name:'Delete Riverlands atlas',exact:true});await remove.click();const dialog=page.getByRole('dialog',{name:'Delete asset?',exact:true});await expect(dialog).toContainText('Riverlands atlas');await expect(dialog).toContainText('Remove this asset from the library?');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(deletions).toHaveLength(0);await expect(remove).toBeVisible();await remove.click();await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(remove).toHaveCount(0);expect(deletions).toHaveLength(1);expect(deletions[0].operationId).toMatch(/^[a-f0-9]{32}$/);await page.route('**/assets/delete',route=>route.fulfill({status:409,json:{error:'This asset is used by a scene. Choose another scene image before deleting it.'},headers:{'access-control-allow-origin':origin}}));await page.getByRole('button',{name:'Delete Keep floor plan',exact:true}).click();await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('used by a scene');await expect(page.getByRole('button',{name:'Delete Keep floor plan',exact:true,includeHidden:true})).toHaveCount(1);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>document.querySelectorAll('button button').length)).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});


for(const width of [1280,390])test(`Assets includes portraits, videos and custom semantic kinds with full upload choices at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});await fixture(page,context);
 const assets=[{key:key('face'),name:'image.png',kind:'portrait',contentType:'image/png',metadata:{title:'Scout portrait'}},{key:'games/test-game/assets/action/original/take.mp4',name:'take.mp4',kind:'video',contentType:'video/mp4',metadata:{title:'River crossing'}},{key:key('battle'),name:'image.png',kind:'battle-map',contentType:'image/png',metadata:{title:'Battle field'}},{key:'games/test-game/assets/internal/original/provenance.json',name:'provenance.json',kind:'generation-provenance',contentType:'application/json',metadata:{title:'Hidden provenance'}}];
 await context.route(`${api}/assets?**`,route=>route.fulfill({json:{assets,cursor:null},headers:{'access-control-allow-origin':origin}}));
 const videoKey=assets[1].key,thumbnailKey=key('video-thumbnail');await context.route(`${api}/object-url?**`,route=>{const requested=new URL(route.request().url()).searchParams.get('key');if(requested===videoKey)return route.fulfill({json:{key:videoKey,contentType:'video/mp4',thumbnailKey},headers:{'access-control-allow-origin':origin}});if(requested===thumbnailKey)return route.fulfill({json:{key:thumbnailKey,contentType:'image/png',url:'https://media.example/video-thumbnail.png'},headers:{'access-control-allow-origin':origin}});return route.fallback();});await context.route('https://media.example/video-thumbnail.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6ZQAAAABJRU5ErkJggg==','base64')}));
 await page.goto(`${origin}/games/test-game/assets`);const library=page.getByRole('region',{name:'Assets',exact:true});
 await expect(library.getByRole('button',{name:'Scout portrait Portrait · PNG',exact:true})).toBeVisible();await expect(library.getByRole('button',{name:'River crossing Video · MP4',exact:true})).toBeVisible();await expect(library).not.toContainText('Hidden provenance');
 const thumbnail=library.getByRole('button',{name:'River crossing Video · MP4',exact:true}).locator('img');await expect(thumbnail).toBeVisible();await expect.poll(()=>thumbnail.evaluate(image=>image.complete&&image.naturalWidth>0)).toBe(true);
 await library.getByRole('button',{name:'Portraits',exact:true}).click();await expect(library.getByRole('button',{name:'Scout portrait Portrait · PNG',exact:true})).toBeVisible();await expect(library.getByRole('button',{name:'River crossing Video · MP4',exact:true})).toHaveCount(0);await library.getByRole('button',{name:'Battle map',exact:true}).click();await expect(library.getByRole('button',{name:'Battle field Battle map · PNG',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Upload',exact:true}).click();const form=page.getByRole('form',{name:'Upload asset',exact:true});await form.getByRole('combobox',{name:'Asset type',exact:true}).click();for(const name of ['Portrait','Artwork','Video','Audio','Document','3D','Battle map','Other'])await expect(page.getByRole('option',{name,exact:true})).toBeVisible();await page.getByRole('option',{name:'Portrait',exact:true}).click();await expect(form.getByRole('combobox',{name:'Asset type',exact:true})).toHaveText('Portrait');await form.getByRole('button',{name:'Cancel',exact:true}).click();
});

for(const width of [1280,390])test(`Portrait generation requires a real selected character at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});const{generations}=await fixture(page,context);
 await context.route(`${api}/characters?**`,route=>route.fulfill({json:{characters:[{id:'scout',name:'Lantern Scout'}],cursor:null},headers:{'access-control-allow-origin':origin}}));
 await page.goto(`${origin}/games/test-game/assets`);await page.getByRole('button',{name:'Generate',exact:true}).click();const form=page.getByRole('form',{name:'Generate asset',exact:true});await form.getByRole('combobox',{name:'Asset type',exact:true}).click();await page.getByRole('option',{name:'Portrait',exact:true}).click();await form.getByLabel('Name',{exact:true}).fill('Scout portrait');await form.getByLabel('Prompt',{exact:true}).fill('A traveler holding a lantern at dusk.');await expect(form.getByRole('button',{name:'Generate asset',exact:true})).toBeDisabled();await form.getByRole('combobox',{name:'Character',exact:true}).click();await page.getByRole('option',{name:'Lantern Scout',exact:true}).click();await form.getByRole('button',{name:'Generate asset',exact:true}).click();await expect(page.getByRole('button',{name:'Open asset',exact:true})).toBeVisible();expect(generations[0]).toMatchObject({type:'portrait',characterId:'scout'});
});

for(const width of [1280,390])test(`Asset tag and character filters keep selected chips inside fixed controls at ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:900});await fixture(page,context);
 const both={key:key('crew'),name:'image.png',kind:'portrait',contentType:'image/png',metadata:{title:'Ronin and Maximus',tags:['canonical','night'],characterIds:['ronin','maximus']}};
 const assets=[both,{...both,key:key('ronin'),metadata:{title:'Ronin alone',tags:['canonical'],characterIds:['ronin']}},{...both,key:key('unrelated'),metadata:{title:'Another crew',tags:['night'],characterIds:['maximus']}}];
 await context.route(`${api}/assets?**`,route=>{const more=new URL(route.request().url()).searchParams.has('cursor');return route.fulfill({json:{assets:more?[{...both,key:key('crew-next'),metadata:{...both.metadata,title:'Another shared scene'}}]:assets,cursor:more?null:'next'},headers:{'access-control-allow-origin':origin}});});
 const castReads=[];await context.route(`${api}/characters?**`,route=>{const cursor=new URL(route.request().url()).searchParams.get('cursor');castReads.push(cursor);return route.fulfill({json:{characters:cursor?[{id:'maximus',name:'Maximus'}]:[{id:'ronin',name:'Ronin'}],cursor:cursor?null:'cast-next'},headers:{'access-control-allow-origin':origin}});});
 await context.route(`${api}/tags?**`,route=>route.fulfill({json:{tags:['canonical','night','campaign-only']},headers:{'access-control-allow-origin':origin}}));
 await page.goto(`${origin}/games/test-game/assets`);const library=page.getByRole('region',{name:'Assets',exact:true}),filters=library.locator('.assets-metadata-filters'),typeFilters=library.getByRole('group',{name:'Asset type',exact:true});await expect(filters).toBeVisible();const moreCast=library.getByRole('button',{name:'More character options',exact:true});await expect(moreCast).toBeVisible();expect(castReads).toEqual([null]);await moreCast.click();await expect(moreCast).toHaveCount(0);expect(castReads).toEqual([null,'cast-next']);const before=await filters.boundingBox(),typeBefore=await typeFilters.boundingBox(),initialScroll=await page.evaluate(()=>scrollY);
 for(const [label,values] of [['Tags',['canonical','night']],['Characters',['Ronin','Maximus']]])for(const name of values){await filters.getByRole('combobox',{name:label,exact:true}).click();const search=page.getByRole('combobox',{name:`Search ${label.toLowerCase()}`,exact:true});await expect(search).toBeVisible();const anchor=await filters.getByRole('combobox',{name:label,exact:true}).locator('..').boundingBox();await expect.poll(async()=>Math.abs((await page.locator('.panther-combobox-content[data-state="open"]').boundingBox()).width-anchor.width)).toBeLessThan(2);expect((await page.locator('.panther-combobox-content[data-state="open"]').boundingBox()).width).toBeGreaterThan(150);await search.fill(name.slice(0,3));await search.press('Enter');await expect(filters.getByRole('button',{name:`Remove ${name} from ${label.toLowerCase()}`,exact:true})).toBeVisible();}
 await expect(library.locator('.assets-card')).toHaveCount(1);await expect(library).toContainText('Filtering loaded assets.');await expect(library.getByRole('button',{name:'Ronin and Maximus Portrait · PNG',exact:true})).toBeVisible();const after=await filters.boundingBox();expect(after.height).toBe(before.height);const finalScroll=await page.evaluate(()=>scrollY);expect(after.y+finalScroll).toBe(before.y+initialScroll);expect((await typeFilters.boundingBox()).y+finalScroll).toBe(typeBefore.y+initialScroll);
 for(const control of await filters.locator('.panther-multi-select-control').all()){const bounds=await control.boundingBox();expect(bounds.height).toBe(36);for(const remove of await control.getByRole('button',{name:/^Remove /}).all()){const box=await remove.boundingBox();expect(box.y).toBeGreaterThanOrEqual(bounds.y);expect(box.y+box.height).toBeLessThanOrEqual(bounds.y+bounds.height);expect(box.x).toBeGreaterThanOrEqual(bounds.x);expect(box.x+box.width).toBeLessThanOrEqual(bounds.x+bounds.width);expect(await remove.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);}}
 await library.getByRole('button',{name:'Load more',exact:true}).click();await expect(library.locator('.assets-card')).toHaveCount(2);await expect(library.getByText('Filtering loaded assets.',{exact:false})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath(`assets-filters-${width}.png`)});
});
