const {test,expect}=require('@playwright/test');
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
let server,origin,directory;
test.beforeEach(async()=>{
  directory=fs.mkdtempSync(path.join(os.tmpdir(),'panther-development-browser-'));
  server=spawn('python3',[path.resolve(__dirname,'../../tools/dev_server.py'),'--port','0','--database',path.join(directory,'development.sqlite')],{stdio:['ignore','pipe','pipe']});
  origin=await new Promise((resolve,reject)=>{
    const timer=setTimeout(()=>reject(new Error('Development server did not start')),10000);
    server.once('exit',code=>{clearTimeout(timer);reject(new Error(`Development server exited ${code}`));});
    server.stdout.on('data',chunk=>{const match=chunk.toString().match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});
  });
});
test.afterEach(async()=>{if(server && server.exitCode===null) await new Promise(resolve=>{server.once('exit',resolve);server.kill();});if(directory)fs.rmSync(directory,{recursive:true,force:true});});

for(const width of [1280,390]) test(`development data comes from the database and edits survive a reload at ${width}px`,async({page},testInfo)=>{
  await page.setViewportSize({width,height:900});
  await page.goto(origin+'/account');
  await page.getByRole('button',{name:'Regenerate demo data'}).click();
  await expect(page.getByText('Demo data regenerated.',{exact:true})).toBeVisible();
  await page.goto(origin+'/games/preview-campaign/settings');
  await expect(page.locator('#game-name')).toHaveValue('The Lantern Campaign');
  await page.locator('#game-name').fill('Lantern adventures');
  await page.getByRole('button',{name:'Save game details'}).click();
  await expect(page.locator('#game-settings-status')).toContainText('saved');
  await page.reload();
  await expect(page.locator('#game-name')).toHaveValue('Lantern adventures');
  await page.screenshot({path:testInfo.outputPath(`development-settings-${width}.png`),fullPage:true});
  await expect(page.locator('#game-ruleset')).toBeHidden();
  await expect(page.locator('#game-purpose')).toBeHidden();
  await expect(page.locator('#username')).toBeHidden();
  await expect(page.getByText(/sample data|Example Fantasy System|Your game, your world/i)).toHaveCount(0);
  await page.goto(origin+'/games/preview-campaign/characters');
  await page.getByRole('button',{name:'Add character',exact:true}).click();
  await page.locator('#character-create-form').getByLabel('Character name').fill('Ash Meadow');
  await page.getByRole('button',{name:'Create character',exact:true}).click();
  await expect(page.locator('#character-name')).toHaveText('Ash Meadow');
  await page.reload();
  await expect(page.locator('#character-name')).toHaveText('Ash Meadow');
  await page.screenshot({path:testInfo.outputPath(`development-character-${width}.png`),fullPage:true});
  await page.goto(origin+'/games/preview-campaign/novel');
  await page.getByRole('button',{name:'Add chapter',exact:true}).click();
  await page.locator('#manual-chapter-form').getByLabel('Chapter title').fill('The northern gate');
  await page.locator('#manual-chapter-form').getByLabel('Chapter text').fill('A lantern burned beside the northern gate.');
  await page.locator('#manual-chapter-form').getByRole('button',{name:'Add chapter',exact:true}).click();
  await expect(page.locator('#novel-title')).toHaveText('The northern gate');
  await page.reload();
  await expect(page.locator('#novel-prose')).toContainText('A lantern burned');
  await page.screenshot({path:testInfo.outputPath(`development-chapter-${width}.png`),fullPage:true});
  await page.goto(origin+'/games/preview-campaign/videos');
  await page.getByRole('button',{name:'Create episode',exact:true}).click();
  await page.getByLabel('Episode title',{exact:true}).fill('The northern gate');
  await page.locator('form').filter({has:page.getByLabel('Episode title',{exact:true})}).getByRole('button',{name:'Create episode',exact:true}).click();
  await page.getByRole('button',{name:'Add scene',exact:true}).click();
  await page.getByLabel('Scene title',{exact:true}).fill('Ash Meadow watches the northern gate');
  await page.locator('form').filter({has:page.getByLabel('Scene title',{exact:true})}).getByRole('button',{name:'Add scene',exact:true}).click();
  await page.getByRole('button',{name:'Generate video',exact:true}).click();
  const videoComposer=page.locator('#editorial-video-composer');
  await videoComposer.getByLabel('Ash Meadow',{exact:true}).check();
  await expect(videoComposer.getByLabel('Prompt',{exact:true})).toHaveValue('Ash Meadow watches the northern gate');
  await videoComposer.locator('form').getByRole('button',{name:'Generate',exact:true}).click();
  await expect(videoComposer.getByRole('region',{name:'Video progress'})).toContainText('Processing');
  await page.reload();
  await expect(page.getByText('The northern gate',{exact:true}).first()).toBeVisible();
  await expect(page.locator('#scene-work-progress')).toContainText('Processing');
  await page.goto(origin+'/games/preview-campaign/dashboard');
  await expect(page.locator('#dashboard-recent').getByRole('link',{name:'The northern gate'})).toBeVisible();
  await expect(page.locator('#dashboard-recent').getByRole('link',{name:'Ash Meadow'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
  await page.screenshot({path:testInfo.outputPath(`development-dashboard-${width}.png`),fullPage:true});
});

for(const width of [1280,390])test(`Real local map upload feeds a pinned scene after reload at ${width}px`,async({page},testInfo)=>{
 await page.setViewportSize({width,height:900});await page.goto(origin+'/account');await page.getByRole('button',{name:'Regenerate demo data'}).click();await expect(page.getByText('Demo data regenerated.',{exact:true})).toBeVisible();
 await page.goto(origin+'/games/preview-campaign/assets');const library=page.getByRole('region',{name:'Assets',exact:true});await library.getByRole('button',{name:'Maps',exact:true}).click();await library.getByRole('button',{name:'Upload',exact:true}).click();const form=library.getByRole('form',{name:'Upload asset',exact:true});await form.getByLabel('Name (optional)',{exact:true}).fill('Northern route');
 const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=480;canvas.height=240;const c=canvas.getContext('2d');c.fillStyle='#e6d5aa';c.fillRect(0,0,480,240);c.fillStyle='#39392e';c.font='20px serif';c.fillText('Harbor',40,180);c.fillText('Hills',340,60);return canvas.toDataURL('image/png').split(',')[1];});await form.getByLabel('File',{exact:true}).setInputFiles({name:'route.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await form.getByRole('button',{name:'Upload asset',exact:true}).click();await expect(library.getByRole('button',{name:'Northern route Map',exact:true})).toBeVisible();await page.reload();await expect(library.getByRole('button',{name:'Northern route Map',exact:true})).toBeVisible();
 await page.goto(origin+'/games/preview-campaign/videos');await page.getByRole('button',{name:'Create episode',exact:true}).click();await page.getByLabel('Episode title',{exact:true}).fill('A journey');await page.getByRole('form',{name:'Episode editor'}).getByRole('button',{name:'Create episode',exact:true}).click();await page.getByRole('button',{name:'Add scene',exact:true}).click();const editor=page.getByRole('form',{name:'Scene editor'});await editor.getByLabel('Scene title',{exact:true}).fill('Travel from Harbor to Hills');await editor.getByRole('combobox',{name:'Scene type',exact:true}).click();await page.getByRole('option',{name:'Map',exact:true}).click();await editor.getByRole('combobox',{name:'Map image',exact:true}).click();await page.getByRole('option',{name:'Northern route',exact:true}).click();await editor.getByRole('button',{name:'Add scene',exact:true}).click();await page.getByRole('button',{name:'Generate video',exact:true}).click();const composer=page.locator('#editorial-video-composer');await expect(composer.getByAltText('Selected map',{exact:true})).toBeVisible();await composer.getByRole('button',{name:'Generate',exact:true}).click();await expect(composer).toContainText('Processing');await page.reload();await expect(page.locator('#scene-work-progress')).toContainText('Processing');
 await page.goto(origin+'/games/preview-campaign/assets');await library.getByRole('button',{name:'Generate',exact:true}).click();const generate=library.getByRole('form',{name:'Generate asset'});await generate.getByLabel('Name',{exact:true}).fill('New coast');await generate.getByLabel('Prompt',{exact:true}).fill('A regional coastline map with a harbor and hills.');await generate.getByRole('button',{name:'Generate asset',exact:true}).click();await expect(library.getByRole('status').filter({hasText:'Queued'})).toBeVisible();await page.reload();await expect(library.getByRole('status').filter({hasText:'Queued'})).toBeVisible();await expect(library.getByRole('button',{name:'Open asset',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:testInfo.outputPath(`real-local-assets-${width}.png`),fullPage:true});
});
