const {test,expect}=require('@playwright/test');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
let server,origin,directory;
test.beforeEach(async()=>{directory=fs.mkdtempSync(path.join(os.tmpdir(),'panther-dialog-contract-'));server=spawn('python3',[path.resolve(__dirname,'../../tools/dev_server.py'),'--port','0','--database',path.join(directory,'development.sqlite')],{stdio:['ignore','pipe','pipe']});origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Local server did not start')),10000);server.once('exit',code=>{clearTimeout(timer);reject(new Error(`Local server exited ${code}`));});server.stdout.on('data',chunk=>{const match=chunk.toString().match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});});});
test.afterEach(async()=>{if(server&&server.exitCode===null)await new Promise(resolve=>{server.once('exit',resolve);server.kill();});if(directory)fs.rmSync(directory,{recursive:true,force:true});});
async function hit(locator){await expect(locator).toBeVisible();expect(await locator.evaluate(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);}
async function inspect(page,name,width){const dialog=page.getByRole('dialog',{name,exact:true});await expect(dialog).toBeVisible();await dialog.evaluate(async el=>await Promise.all(el.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));const close=dialog.locator('[data-slot=dialog-close]:visible');await expect(close).toHaveCount(1);await hit(close);const closeBox=await close.boundingBox();expect(closeBox.width).toBe(44);expect(closeBox.height).toBe(44);expect(await close.evaluate(el=>getComputedStyle(el).borderWidth)).toBe('0px');await expect(close.locator('svg.lucide-x')).toHaveCount(1);const footer=dialog.locator('[data-slot=dialog-footer]');await expect(footer).toHaveCount(1);const appearance=await footer.evaluate(el=>{const c=getComputedStyle(el);return{background:c.backgroundColor,border:c.borderWidth,padding:c.padding,justify:c.justifyContent};});expect(appearance).toEqual({background:'rgba(0, 0, 0, 0)',border:'0px',padding:'16px 0px 0px',justify:'flex-end'});const buttons=footer.getByRole('button');for(const button of await buttons.all()){if(await button.isEnabled())await hit(button);else await expect(button).toBeVisible();expect((await button.boundingBox()).height).toBe(36);}const cancel=footer.getByRole('button',{name:'Cancel',exact:true});await expect(cancel).toBeVisible();const styles=await cancel.evaluate(el=>{const c=getComputedStyle(el);return{background:c.backgroundColor,color:c.color,border:c.borderWidth};});const box=await dialog.boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);return{dialog,cancel,styles};}
for(const width of [1280,390])test(`Shared form dialogs have consistent footer and close controls at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.goto(origin+'/account');await page.getByRole('button',{name:'Regenerate demo data'}).click();await expect(page.getByText('Demo data regenerated.',{exact:true})).toBeVisible();await page.goto(origin+'/games/preview-campaign/dashboard');
 await page.getByRole('button',{name:'Create Game',exact:true}).click();let result=await inspect(page,'Create Game',width),cancelStyle=result.styles;await result.cancel.click();await expect(result.dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'Create Game',exact:true})).toBeFocused();
 await page.goto(origin+'/games/preview-campaign/characters');await page.getByRole('button',{name:'Create Character',exact:true}).click();result=await inspect(page,'Create Character',width);expect(result.styles).toEqual(cancelStyle);await page.keyboard.press('Escape');await expect(result.dialog).toHaveCount(0);
 await page.goto(origin+'/games/preview-campaign/novel');await page.getByRole('button',{name:'Create Chapter',exact:true}).filter({visible:true}).click();result=await inspect(page,'Create Chapter',width);expect(result.styles).toEqual(cancelStyle);await result.dialog.getByLabel('Chapter title').fill('The harbor crossing');await result.dialog.getByRole('textbox',{name:'Chapter text',exact:true}).fill('The companions crossed the harbor.');await result.dialog.getByRole('combobox',{name:'References',exact:true}).click();await expect(page.getByRole('combobox',{name:'Search references',exact:true})).toBeFocused();await expect(page.getByRole('dialog',{name:'Create Chapter',exact:true,includeHidden:true})).toBeVisible();await page.keyboard.press('Escape');await expect(result.dialog).toBeVisible();await expect(page.getByRole('combobox',{name:'References',exact:true})).toBeFocused();await page.screenshot({path:info.outputPath(`standard-chapter-dialog-${width}.png`),fullPage:true});await page.keyboard.press('Escape');await expect(result.dialog).toHaveCount(0);
 await page.goto(origin+'/games/preview-campaign/episodes');await page.getByRole('button',{name:'Create Episode',exact:true}).click();result=await inspect(page,'Create Episode',width);expect(result.styles).toEqual(cancelStyle);await result.dialog.getByLabel('Episode title',{exact:true}).fill('The harbor crossing');await result.dialog.getByRole('button',{name:'Create Episode',exact:true}).click();await page.getByRole('button',{name:'Create Scene',exact:true}).click();result=await inspect(page,'Create Scene',width);expect(result.styles).toEqual(cancelStyle);await result.dialog.getByRole('combobox',{name:'Scene type',exact:true}).click();await page.getByRole('option',{name:'Map',exact:true}).click();await expect(result.dialog).toBeVisible();await page.screenshot({path:info.outputPath(`standard-scene-dialog-${width}.png`),fullPage:true});await page.keyboard.press('Escape');await expect(result.dialog).toHaveCount(0);
 await page.goto(origin+'/games/preview-campaign/assets');await page.getByRole('button',{name:'Upload',exact:true}).click();result=await inspect(page,'Upload asset',width);expect(result.styles).toEqual(cancelStyle);await result.cancel.click();await expect(result.dialog).toHaveCount(0);
 await page.goto(origin+'/games/preview-campaign/settings');await page.getByRole('button',{name:'Add Tag',exact:true}).click();result=await inspect(page,'Add Tag',width);expect(result.styles).toEqual(cancelStyle);await result.cancel.click();await expect(result.dialog).toHaveCount(0);
});

for(const width of [1280,390])test(`Media preview retains its compact layout and standard close control at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.goto(origin+'/account');await page.getByRole('button',{name:'Regenerate demo data'}).click();await expect(page.getByText('Demo data regenerated.',{exact:true})).toBeVisible();await page.goto(origin+'/games/preview-campaign/assets');await page.getByRole('button',{name:'Upload',exact:true}).click();const form=page.getByRole('form',{name:'Upload asset',exact:true}),title='The companions approach the northern harbor beneath the evening lanterns';await form.getByLabel('Name (optional)',{exact:true}).fill(title);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d');x.fillStyle='#d9be8e';x.fillRect(0,0,320,240);x.fillStyle='#304f58';x.fillRect(130,0,60,240);return c.toDataURL('image/png').split(',')[1];});await form.getByLabel('File',{exact:true}).setInputFiles({name:'harbor.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await form.getByRole('button',{name:'Upload asset',exact:true}).click();const card=page.locator('.assets-card').filter({hasText:title});await card.click();const dialog=page.locator('.panther-dialog-content[data-dialog-variant=media]');await expect(dialog).toBeVisible();await dialog.evaluate(async el=>await Promise.all(el.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));const close=dialog.locator('[data-slot=dialog-close]:visible');await expect(close).toHaveCount(1);await expect(close.locator('svg.lucide-x')).toHaveCount(1);await hit(close);expect((await close.boundingBox()).width).toBe(44);expect((await close.boundingBox()).height).toBe(44);expect(await close.evaluate(el=>getComputedStyle(el).borderWidth)).toBe('0px');await expect(dialog.locator('[data-slot=dialog-footer]')).toHaveCount(0);expect(await dialog.evaluate(el=>getComputedStyle(el).padding)).toBe('0px');await expect(dialog.getByRole('link',{name:'Download',exact:true})).toBeVisible();await expect.poll(()=>dialog.locator('#preview-body img').evaluate(image=>image.complete&&image.naturalWidth)).toBe(320);await expect(dialog.getByRole('button',{name:/Download|Open original|Technical files/})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`standard-media-dialog-${width}.png`),fullPage:true});await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(card).toBeFocused();
});
