const {test,expect}=require('@playwright/test');
const {spawn}=require('node:child_process');
const crypto=require('node:crypto');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
let server,origin,directory;
test.beforeEach(async({page})=>{
 directory=fs.mkdtempSync(path.join(os.tmpdir(),'panther-user-journey-'));
 server=spawn('python3',[path.resolve(__dirname,'../../tools/dev_server.py'),'--port','0','--database',path.join(directory,'data.sqlite')]);
 origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('API did not start')),10000);server.once('exit',code=>{clearTimeout(timer);reject(new Error(`API exited ${code}`));});server.stdout.on('data',chunk=>{const match=chunk.toString().match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});});
 await page.goto(origin+'/account');await page.getByRole('button',{name:'Regenerate demo data',exact:true}).click();await expect(page.getByText('Demo data regenerated.',{exact:true})).toBeVisible();
});
test.afterEach(async()=>{if(server&&server.exitCode===null)await new Promise(resolve=>{server.once('exit',resolve);server.kill();});if(directory)fs.rmSync(directory,{recursive:true,force:true});});
const headers={Authorization:'Bearer synthetic-audit-user'};
async function uploadTranscript(page){
 const document={entityType:'PlayerTranscript',gameId:'preview-campaign',players:[{id:'alex',name:'Alex'}],segments:[{start:0,end:2,playerId:'alex',text:'The gate opens.'},{start:2,end:4,playerId:null,text:'Who brought the lantern?'}]};
 const bytes=Buffer.from(JSON.stringify(document)),checksum=crypto.createHash('sha256').update(bytes).digest('base64');
 const reservation=await page.request.post(origin+'/uploads',{headers,data:{gameId:'preview-campaign',assetId:'audit-transcript',kind:'raw-transcript',filename:'raw.json',size:bytes.length,contentType:'application/json',sha256:checksum,metadata:{title:'The gate',sessionId:'audit-session',category:'reference'}}});
 expect(reservation.ok()).toBe(true);const signed=await reservation.json();
 const saved=await page.request.put(signed.url,{headers:signed.headers,data:bytes});expect(saved.ok()).toBe(true);return signed.key;
}
for(const width of [1280,390]){
 test(`Real user can create, find, read and revisit campaign content at ${width}px`,async({page},testInfo)=>{
  test.setTimeout(90000);await page.setViewportSize({width,height:900});const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(origin+'/games/preview-campaign/characters');await page.getByRole('button',{name:'Create Character',exact:true}).click();await page.locator('#character-create-form').getByLabel('Character name').fill('River Scout');await page.getByRole('button',{name:'Create Character',exact:true}).click();await expect(page.locator('#character-name')).toHaveText('River Scout');const characterUrl=page.url();await page.reload();await expect(page.locator('#character-name')).toHaveText('River Scout');
  await page.goto(origin+'/games/preview-campaign/novel');await page.getByRole('button',{name:'Create Chapter',exact:true}).filter({visible:true}).click();const chapter=page.locator('#manual-chapter-form');await chapter.getByLabel('Chapter title').fill('The river gate');await chapter.getByLabel('Chapter text').fill('The River Scout raised a lantern beside the gate.');await chapter.getByRole('button',{name:'Create Chapter',exact:true}).click();await expect(page.locator('#novel-prose')).toContainText('raised a lantern');await page.reload();await expect(page.locator('#novel-title')).toHaveText('The river gate');
  await page.goto(origin+'/games/preview-campaign/episodes');await page.getByRole('button',{name:'Create Episode',exact:true}).click();const episode=page.getByRole('form',{name:'Episode editor'});await episode.getByLabel('Episode title',{exact:true}).fill('The river gate');await episode.getByRole('button',{name:'Create Episode',exact:true}).click();await page.getByRole('button',{name:'Create Scene',exact:true}).click();const scene=page.getByRole('form',{name:'Scene editor'});await scene.getByLabel('Scene title',{exact:true}).fill('Lantern at the gate');await scene.getByRole('button',{name:'Create Scene',exact:true}).click();await expect(page.locator('.selected-scene')).toContainText('Lantern at the gate');const sceneUrl=page.url();await page.reload();await expect(page.locator('.selected-scene')).toContainText('Lantern at the gate');await page.locator('#scene-header-actions').getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('form',{name:'Scene editor'}).getByLabel('Scene title',{exact:true}).fill('Unsaved change');await page.getByRole('form',{name:'Scene editor'}).getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('.selected-scene')).toContainText('Lantern at the gate');
  await page.goto(origin+'/games/preview-campaign/assets');await page.getByRole('button',{name:'Upload',exact:true}).click();const form=page.getByRole('form',{name:'Upload asset'});await form.getByLabel('Name (optional)',{exact:true}).fill('Gate notes');await form.getByLabel('File',{exact:true}).setInputFiles({name:'gate.txt',mimeType:'text/plain',buffer:Buffer.from('A gate beside the river.')});await form.getByRole('button',{name:'Upload asset',exact:true}).click();await expect(page.locator('.assets-card-title').filter({hasText:'Gate notes'})).toHaveCount(1);await page.reload();await expect(page.locator('.assets-card-title').filter({hasText:'Gate notes'})).toHaveCount(1);
  await page.goto(origin+'/games/preview-campaign/dashboard');for(const label of ['River Scout','The river gate'])await expect(page.locator('#dashboard-sections').getByRole('link',{name:label,exact:true}).first()).toBeVisible();await page.locator('#dashboard-sections [data-section="characters"]').getByRole('link',{name:'River Scout',exact:true}).click();await expect(page).toHaveURL(characterUrl);await page.goto(sceneUrl);await expect(page.locator('.selected-scene')).toContainText('Lantern at the gate');expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:testInfo.outputPath(`real-user-journey-${width}.png`),animations:'disabled',fullPage:true});
 });
 test(`Sessions recovers from a real catalog interruption at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});await uploadTranscript(page);let fail=true;
  await page.route('**/assets?**',route=>fail&&new URL(route.request().url()).searchParams.get('section')==='sessions'?route.fulfill({status:503,json:{error:'Catalog temporarily unavailable'}}):route.continue());
  await page.goto(origin+'/games/preview-campaign/sessions');await expect(page.locator('#library-status')).toContainText('temporarily unavailable');fail=false;await page.getByRole('button',{name:'Retry sessions',exact:true}).click();await expect(page.getByRole('link',{name:'Original transcript',exact:true})).toBeVisible();
 });
 test(`Assets recovers without discarding its search at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});let fail=true;await page.route('**/assets?**',route=>fail?route.fulfill({status:503,json:{error:'Asset catalog interrupted'}}):route.continue());await page.goto(origin+'/games/preview-campaign/assets');await expect(page.getByRole('alert')).toContainText('interrupted');await page.getByRole('searchbox',{name:'Search assets'}).fill('lantern');fail=false;await page.getByRole('button',{name:'Retry assets',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByRole('searchbox',{name:'Search assets'})).toHaveValue('lantern');await expect(page.getByText('No matching assets.',{exact:true})).toBeVisible();
 });
 test(`Workflow browsing can recover and leave a broken deep link at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});let fail=true;await page.route('**/workflows?**',route=>fail?route.fulfill({status:503,json:{error:'Workflow service interrupted'}}):route.continue());await page.goto(origin+'/games/preview-campaign/workflows');await expect(page.getByRole('alert')).toContainText('interrupted');fail=false;await page.getByRole('button',{name:'Retry workflows',exact:true}).click();await expect(page.getByText('No workflows yet.',{exact:true})).toBeVisible();await page.goto(origin+'/games/preview-campaign/workflows/editorial/missing');await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('link',{name:'Back to workflow runs',exact:true}).click();await expect(page).toHaveURL(/workflows\/editorial$/);await expect(page.getByText('No runs yet.',{exact:true})).toBeVisible();
 });
 test(`Unidentified transcript speech is explicitly labeled and searchable at ${width}px`,async({page},testInfo)=>{
  await page.setViewportSize({width,height:900});await uploadTranscript(page);await page.goto(origin+'/games/preview-campaign/sessions');await page.getByRole('link',{name:'Original transcript',exact:true}).click();const unknown=page.locator('.transcript-segment').filter({hasText:'Who brought the lantern?'});await expect(unknown).toContainText('Unidentified speaker');await page.getByRole('searchbox',{name:'Search transcript'}).fill('Unidentified speaker');await expect(unknown).toHaveClass(/transcript-match/);await page.screenshot({path:testInfo.outputPath(`unidentified-transcript-${width}.png`),animations:'disabled'});
 });
 test(`A recording does not silently disappear when its playback request fails at ${width}px`,async({page},testInfo)=>{
  await page.setViewportSize({width,height:900});
  const bytes=fs.readFileSync(path.join(__dirname,'synthetic-continuous.mp3')),checksum=crypto.createHash('sha256').update(bytes).digest('base64');
  const response=await page.request.post(origin+'/uploads',{headers,data:{gameId:'preview-campaign',assetId:'audit-audio',kind:'recording-playback',filename:'playback.mp3',size:bytes.length,contentType:'audio/mpeg',sha256:checksum,metadata:{title:'The gate recording',sessionId:'audit-session',category:'reference'}}});expect(response.ok()).toBe(true);const signed=await response.json();expect((await page.request.put(signed.url,{headers:signed.headers,data:bytes})).ok()).toBe(true);
  let fail=true;await page.route('**/object-url?**',route=>fail?route.fulfill({status:503,json:{error:'Playback connection interrupted'}}):route.continue());await page.goto(origin+'/games/preview-campaign/sessions');const card=page.locator('.session-card');await expect(card.getByRole('alert')).toContainText('Playback connection interrupted');await expect(card.getByRole('button',{name:'Download audio',exact:true})).toBeVisible();fail=false;await card.getByRole('button',{name:'Retry recording',exact:true}).click();await expect(card.getByRole('alert')).toHaveCount(0);await expect(card.locator('audio')).toBeVisible();await expect(card.locator('audio')).toHaveAttribute('src',/development\/object/);await page.screenshot({path:testInfo.outputPath(`recording-recovery-${width}.png`),animations:'disabled'});
 });
 test(`A transient summary failure has a read-only recovery at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});await uploadTranscript(page);let fail=true;const methods=[];await page.route('**/transcript-summaries?**',route=>{methods.push(route.request().method());return fail?route.fulfill({status:503,json:{error:'Summary interrupted'}}):route.continue();});await page.goto(origin+'/games/preview-campaign/sessions');await expect(page.getByRole('alert')).toContainText('Summary unavailable');fail=false;await page.getByRole('button',{name:'Retry summary',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByRole('link',{name:'Original transcript',exact:true})).toBeVisible();expect(methods.every(method=>method==='GET')).toBe(true);
 });
}
