import React,{useId,useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useEditor,EditorContent} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import {Markdown} from '@tiptap/markdown';
import {TableKit} from '@tiptap/extension-table';
import Image from '@tiptap/extension-image';
import {Bold,Italic,Heading2,List,ListOrdered,Quote,Undo2,Redo2,Code2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from './components/ui/dialog.jsx';
import {Button} from './components/ui/button.jsx';
import {Input} from './components/ui/input.jsx';
import {MultiSelect} from './components/ui/multi-select.jsx';
const ManuscriptImage=Image.extend({renderHTML({node}){return ['span',{'data-manuscript-image':''},node.attrs.alt||'Image'];}});
export function ChapterEditor({previous,gameId,scope,onLoadReferences,onSave,onClose,onComplete}){
 const id=useId(),[title,setTitle]=useState(previous?.title||''),[sources,setSources]=useState(previous?.details?.sourceKeys||[]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(false),[,redraw]=useState(0),pending=useRef(null);
 const editor=useEditor({extensions:[StarterKit.configure({underline:false,link:{openOnClick:false}}),Markdown,TableKit,ManuscriptImage],content:previous?.markdown||'',contentType:'markdown',editorProps:{attributes:{role:'textbox','aria-label':'Chapter text','aria-multiline':'true',class:'chapter-writing-surface'}},onUpdate:()=>redraw(n=>n+1),onSelectionUpdate:()=>redraw(n=>n+1)});
 const refs=useQuery({queryKey:['chapter-references',scope,gameId],queryFn:onLoadReferences,staleTime:60000});
 const submit=async event=>{event.preventDefault();const markdown=editor?.getMarkdown().trim();if(busy||!title.trim()||!markdown)return;setBusy(true);setError('');editor.setEditable(false);try{pending.current||={gameId,title:title.trim(),markdown,sourceKeys:sources,operationId:crypto.randomUUID().replaceAll('-',''),previousChapterId:previous?.id||null};const result=await onSave(pending.current);onComplete(result);}catch(e){setError(e.message||'Could not save the chapter. Your writing is still here.');if(e.status===400||e.status===409){pending.current=null;setRetry(false);editor.setEditable(true);}else setRetry(true);}finally{setBusy(false);}};
 const tools=[['Bold',Bold,()=>editor.chain().focus().toggleBold().run(),'bold'],['Italic',Italic,()=>editor.chain().focus().toggleItalic().run(),'italic'],['Heading',Heading2,()=>editor.chain().focus().toggleHeading({level:2}).run(),'heading'],['Bullet list',List,()=>editor.chain().focus().toggleBulletList().run(),'bulletList'],['Numbered list',ListOrdered,()=>editor.chain().focus().toggleOrderedList().run(),'orderedList'],['Quote',Quote,()=>editor.chain().focus().toggleBlockquote().run(),'blockquote'],['Code',Code2,()=>editor.chain().focus().toggleCodeBlock().run(),'codeBlock'],['Undo',Undo2,()=>editor.chain().focus().undo().run()],['Redo',Redo2,()=>editor.chain().focus().redo().run()]];
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="chapter-editor-dialog" aria-label={previous?'Edit Chapter':'Create Chapter'} onInteractOutside={event=>event.preventDefault()} onEscapeKeyDown={event=>{if(busy)event.preventDefault();}}><DialogHeader><DialogTitle>{previous?'Edit Chapter':'Create Chapter'}</DialogTitle><DialogDescription className="sr-only">Write a chapter and optionally connect its source references.</DialogDescription></DialogHeader><form id="manual-chapter-form" onSubmit={submit} className="chapter-editor-form"><div className="chapter-editor-body"><div className="chapter-title-field"><label htmlFor={`${id}-title`}>Chapter title</label><Input id={`${id}-title`} required maxLength={160} autoFocus value={title} disabled={busy||retry} onChange={e=>setTitle(e.target.value)}/></div><div className="chapter-writing"><div role="toolbar" aria-label="Writing tools" className="chapter-writing-toolbar">{tools.map(([label,Icon,command,mark])=><Button key={label} type="button" variant={mark&&editor?.isActive(mark)?'secondary':'ghost'} size="icon" aria-label={label} title={label} aria-pressed={mark?Boolean(editor?.isActive(mark)):undefined} disabled={!editor||busy||retry} onClick={command}><Icon size={16}/></Button>)}</div><EditorContent editor={editor}/></div><MultiSelect modal label="References" placeholder="Add Reference…" options={refs.data||[]} value={sources} onChange={setSources} disabled={busy||retry}/>{refs.isError&&<p role="alert">References unavailable. You can still save your chapter.</p>}{error&&<p role="alert" className="chapter-editor-error">{error}</p>}</div><DialogFooter className="chapter-editor-footer"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy||!title.trim()||!editor?.getText().trim()}>{busy?'Saving…':retry?'Retry Save':previous?'Save Chapter':'Create Chapter'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
