// Display choices, not a closed schema: custom systems remain ordinary ruleset text.
export const GAME_SYSTEMS = [
  'Dungeons & Dragons — 5.5e (2024)',
  'Dungeons & Dragons — 5e (2014)',
  'Dungeons & Dragons — 4e',
  'Dungeons & Dragons — 3.5e',
  'Advanced Dungeons & Dragons — 2e',
  'Pathfinder — 2e Remaster',
  'Pathfinder — 2e (original)',
  'Pathfinder — 1e',
  'Starfinder — 1e',
  'Call of Cthulhu — 7e',
  'RuneQuest — Roleplaying in Glorantha',
  'Pendragon — 6e',
  'Warhammer Fantasy Roleplay — 4e',
  'Cyberpunk RED',
  'Shadowrun — 6e',
  'Traveller — Mongoose 2e',
  'Savage Worlds — Adventure Edition',
  'Fate Core',
  'Fate Accelerated',
  'Blades in the Dark',
  'Dungeon World',
  'Monster of the Week',
  'The One Ring — 2e',
  'Alien — RPG',
  'Vampire: The Masquerade — 5e',
  'Daggerheart',
  'Shadowdark',
  'Fabula Ultima',
  'Mörk Borg',
  'Mausritter',
  'Lancer',
  'Numenera — Discovery & Destiny',
];
export function isKnownGameSystem(value) { return GAME_SYSTEMS.includes(value); }
