import test from 'node:test';
import assert from 'node:assert/strict';
import {LiveTranscription} from '../src/live-transcription.js';
class Socket{static OPEN=1;static connections=[];constructor(url,protocols){this.url=url;this.protocols=protocols;this.readyState=1;this.sent=[];this.events=new Map();Socket.connections.push(this);}addEventListener(type,callback){if(!this.events.has(type))this.events.set(type,[]);this.events.get(type).push(callback);}emit(type,data){for(const callback of this.events.get(type)||[])callback({data:JSON.stringify(data)});}send(raw){this.sent.push(JSON.parse(raw));}close(){this.readyState=3;this.emit('close',{});}}
test('live speech deltas stream without batch inference, silence commits or automatic reconnect',async()=>{globalThis.WebSocket=Socket;Socket.connections=[];const text=[],events=[];let failures=0;const transport=new LiveTranscription({onText:(...args)=>text.push(args),onProviderEvent:event=>events.push(event),onError:()=>failures++});const connecting=transport.connect({model:'gpt-live-transcribe',clientSecret:'synthetic-shortlived'}),socket=Socket.connections[0];socket.emit('open',{});socket.emit('message',{type:'session.updated',session:{client_secret:{value:'must-not-persist'}}});await connecting;assert.equal(socket.sent[0].session.audio.input.transcription.model,'gpt-live-transcribe');assert.deepEqual(socket.sent[0].session.audio.input.transcription.languages,['en']);assert.equal(socket.sent[0].session.audio.input.turn_detection,null);assert.equal(JSON.stringify(events).includes('must-not-persist'),false);for(let i=0;i<20;i++)transport.audio(new ArrayBuffer(4800),0);assert.equal(socket.sent.length,1);transport.audio(new ArrayBuffer(4800),.1);assert(socket.sent.some(event=>event.type==='input_audio_buffer.append'));socket.emit('message',{type:'conversation.item.input_audio_transcription.delta',item_id:'one',delta:'Hello'});socket.emit('message',{type:'conversation.item.input_audio_transcription.delta',item_id:'one',delta:' world'});assert.equal(text.at(-1)[1],'Hello world');transport.pause();assert.equal(socket.sent.filter(event=>event.type==='input_audio_buffer.commit').length,1);socket.emit('message',{type:'conversation.item.input_audio_transcription.completed',item_id:'one',transcript:'Hello, world.'});assert.equal(text.at(-1)[1],'Hello, world.');socket.emit('message',{type:'error',error:{code:'rate_limit_exceeded'}});assert(failures>0);assert.equal(Socket.connections.length,1);transport.close();});

test('stop drains acknowledged turns and preserves provider order when completions arrive out of order',async()=>{
 globalThis.WebSocket=Socket;Socket.connections=[];const orders=[],events=[];const transport=new LiveTranscription({onText:()=>{},onError:()=>{},onProviderEvent:event=>events.push(event),onOrder:order=>orders.push(order)});const connecting=transport.connect({model:'gpt-live-transcribe',clientSecret:'synthetic'}),socket=Socket.connections[0];socket.emit('open',{});socket.emit('message',{type:'session.updated'});await connecting;
 transport.audio(new ArrayBuffer(4800),.1);transport.pause();transport.audio(new ArrayBuffer(4800),.1);const finishing=transport.finish();let finished=false;void finishing.then(()=>finished=true);
 socket.emit('message',{type:'input_audio_buffer.committed',item_id:'second',previous_item_id:'first'});socket.emit('message',{type:'conversation.item.input_audio_transcription.completed',item_id:'second',transcript:'Second.'});await Promise.resolve();assert.equal(finished,false);
 socket.emit('message',{type:'input_audio_buffer.committed',item_id:'first',previous_item_id:null});socket.emit('message',{type:'conversation.item.input_audio_transcription.completed',item_id:'first',transcript:'First.'});assert.deepEqual(await finishing,{complete:true,pendingTurns:0});assert.deepEqual(orders.at(-1),['first','second']);assert.equal(events.filter(event=>event.type==='input_audio_buffer.committed').length,2);assert.equal(Socket.connections.length,1);
});
